### PR TITLE
Fix typescript reference issue

### PR DESCRIPTION
**Pull request by tyson-benson**
Given C:\path\to\src\chutzpah.json
And the command C:\path\to\src>ctz chutzpah.json
```
{
  ... other options removed for brevity ...
  "Compile": {
    "UseSourceMaps": true,
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    { "Path": "tests/mocks.ts" },
    { "Path": "../../other-src/code.ts" }
  ]
}
```

I want the chutzpah to build the following references in the harness:
```
<script href="file:///C:/path/to/src/tests/mocks.js"></script>
<script href="file:///C:/path/other-src/code.ts"></script>
```

At present it omits the second Reference as its absolute path does not
start with the directory path of the chutzpah.json file
(BatchCompilerService : line 182)

P.S. I would have written tests against this case, but I couldnt install
the xUnit test runner. The VISX installer crashed.

### CODE REVIEW

**Comment by mmanela** [comment]
Couldn't you just change your configuration to 

```
 "Compile": {
    "UseSourceMaps": true,
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
"Paths" : [
      { "SourcePath": "../../", "OutputPath": "../../" }
    ]
   },
  },

```

**Comment by mmanela** [comment]
@tyson-benson ping

**Comment by mmanela** [comment]
I have not heard back from you. Closing PR for now. But we can re-open if you disagree with my solution.

**Comment by tyson-benson** [comment]
This solution seems to work, thanks for your help :)

**Pull request closed without merging**
