### PR TITLE
Make SourceMapDotNetLineCoverageMapper aware of referenced files in source maps

### PR DESCRIPTION
**Pull request by mattxo**
When running Chutzpah coverage on TypeScript files, an error occurs when processing TypeScript file references when the referenced file is longer than the source file.

This is because in SourceMapDotNetLineCoverageMapper.cs

```
var accumulated = new List<int?>(new int?[sourceLineCount + 1]);`
public int?[] GetOriginalFileLineExecutionCounts(int?[] generatedSourceLineExecutionCounts, int sourceLineCount, string referencedFile)
    {
       ...
       var accumulated = new List<int?>(new int?[sourceLineCount + 1]);
       ...
            var matches = consumer.OriginalPositionsFor(i);
            if (matches.Any())
            {
                foreach (var match in matches)
                {
                    *** Assumes match == the source file under test! It is not, the source map can refer to another file *** 
                    *** Throws System.ArgumentOutOfRangeException when the line number of the matched file is longer than the source file and produces an inaccurate count if by chance sourceLineCount > the line count of the source file referenced in the sourcemap. 
                    accumulated[match.LineNumber] = (accumulated[match.LineNumber] ?? 0) + generatedCount.Value;
                }
            }
        }
        return accumulated.ToArray();
    }
```

The fix is to pass in the ReferencedFile object instead of the sourceMapPath so we can compare whether the match was made in the file we're actually covering or not.

```
                    foreach (var match in matches)
                    {
                        if (match.File != fileSystem.GetFileName(referencedFile.Path)) continue;

                        accumulated[match.LineNumber] = (accumulated[match.LineNumber] ?? 0) + generatedCount.Value;
                    }
```

The error that occurs...

`
Error: System.AggregateException: One or more errors occurred. ---> System.Argum
entOutOfRangeException: Index was out of range. Must be non-negative and less th
an the size of the collection.
Parameter name: index
   at System.Collections.Generic.List1.get_Item(Int32 index)
   at Chutzpah.Coverage.SourceMapDotNetLineCoverageMapper.GetOriginalFileLineExe
cutionCounts(Nullable1[] generatedSourceLineExecutionCounts, Int32 sourceLineCo
unt, String mapFilePath) in c:\Dev\chutzpah\Chutzpah\Coverage\SourceMapDotNetLin
eCoverageMapper.cs:line 55
   at Chutzpah.Coverage.BlanketJsCoverageEngine.DeserializeCoverageObject(String
 json, TestContext testContext) in c:\Dev\chutzpah\Chutzpah\Coverage\BlanketJsCo
verageEngine.cs:line 171
   at Chutzpah.TestCaseStreamReader.FireCoverageObject(ITestMethodRunnerCallback
 callback, TestFileContext testFileContext, JsRunnerOutput jsRunnerOutput) in c:
\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 125
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestCont
ext testContext, TestOptions testOptions, ITestMethodRunnerCallback callback, Bo
olean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 236
`

### CODE REVIEW

**Comment by mattxo** [comment]
*** EventService.ts ***

/// <reference path="../models/event.ts" />

module Lovatts.Web.Sites.YouPlay
{
    export class EventsService
    {
        public toggleDrawerEvent: Event = new Event();        

        constructor()
        {            
        }      
    }
}

When models/event.ts is longer than EventService.ts, Chutzpah throws the exception when running coverage.

**Comment by mmanela** [comment]
@Pablissimo Can you take a look at this?

**Comment by Pablissimo** [comment]
Sure, though on a wedding planning weekend in the middle of nowhere just now - should be able to check it out Monday night?

**Comment by mmanela** [comment]
Thanks, no rush

-----Original Message-----

**Comment by Pablissimo** [comment]
So the fix that you've put in seems fine - but I can't reproduce the failure. Are you using the 'output everything into a single JS file' option of the TypeScript compiler? I couldn't think of another situation where a single generated JS file would map to multiple TS files but I'd be interested to see a repro!

**Comment by mattxo** [comment]
Hi, yep,  it occurs when using the --out flag of the TypeScript compiler. I'll put a repro together tomorrow :) Whats the best way to share it?

**Comment by Pablissimo** [comment]
Either a GitHub repo or email me (email on my profile page), both fine =)

I'll try and repro something myself just now based on that compiler setting...

**Comment by mattxo** [comment]
Ok cool :) Yeah, just referencing something like ref.ts from app.ts and compiling app.ts with --out --sourceMap should make the coverage explode if ref.ts has more lines of code in it than app.ts. Will chuck a repro together tomorrow if I don't hear from you.

**Comment by Pablissimo** [comment]
What're you using for the TS build to only bundle some TS files into the same output file? Also presumably you'd expect only to get coverage numbers for app.ts and not for ref.ts?

**Comment by mattxo** [comment]
Just tsc.exe app.ts --out app.js --sourceMap via gulpjs. Tsc v1.4 and 1.5 beta. What I'm actually doing is running the compiler on every ts file so their dependencies are intact so chutzpah can generate coverage for each of them...

**Comment by Pablissimo** [comment]
Would probably go with your patch then, I think. I could re-architect how the mapping stuff works to support map files that relate to multiple source files but that'd be a bigger change.

**Comment by mattxo** [comment]
*nods* the source map analyzer chutzpah has taken a dependency on already accounts for referenced files, but someone would probably need to rejig the way the values in accumulated are consumed to get proper line execution counts. Anyone using TypeScript and the --out flag to manage dependencies is going to run into the same problem trying to get coverage data.

**Comment by Pablissimo** [comment]
I'm sort-of wondering whether, when sourcemaps are available, the way coverage is needs to work the other way around- rather than starting with the source files that Chutzpah knows about, you start from any map files you've found and work backwards as to what source files were involved (even if Chutzpah wasn't told about them).

Various exciting edge-cases there though...

**Comment by mattxo** [comment]
Hehe, that *would* be fun *grins*

**Comment by Pablissimo** [comment]
It's probably a better reflection of reality though, Blanket tells you what lines of code were run and sourcemaps take you back to 'filenames'. If they happen to match up to actual source files you can find on disk then happy days, but since it's just for reporting I'm not sure it matters that much.

Next time I get a free weekend... =)

**Comment by mattxo** [comment]
Hmm... I *think* it could be problematic to have sourcemaps determining which source files are to be covered, because you'd still need to rely on which source files you've directed chutzpah towards, because just because a source file isn't explicitly referenced, doesn't necessarily mean you don't want it covered. Eg. I have files that I include conditionally in the projects build system, so nobody takes an explicit /// reference to them, but they're still covered via a unit test and I want that coverage report for them. You *could* merge the sourcemap references with other source files you've specified to chutzpah though I suppose in that instance, but I'm not sure it would be much clearer as a consumer specifying map files vs source files. The source files are the ones I want to generate coverage for after all, the maps are just there to translate, not to specify what I want covered...

**Pull request merged**
